### ISSUE TITLE
Direct dependency on 'astroui'

### ISSUE THREAD

**Issue by eckig** [Zeioth/heirline-components.nvim#10]
With the recent changes there is now a direct dependency to 'astroui': https://github.com/Zeioth/heirline-components.nvim/blob/592c4ccfb14e618c2aa05b34296dec0e18926788/lua/heirline-components/core/utils.lua#L174C7-L174C58

Is that intentional?

**Comment by Zeioth** [comment]
* @eckig thank you so much for testing it. Fixed in b262653a06e765f084ade19d3708f949394c8718
* I'm gonna re-test mini.icons before releasing v1.2.4 to ensure everything is working 👍
