### ISSUE TITLE
Currently hard to implement the NvChad-style statusline

### ISSUE THREAD

**Issue by vollowx** [Zeioth/heirline-components.nvim#2]
It's possible to do this with AstroNvim as the [docs](https://docs.astronvim.com/recipes/status/#replicate-nvchad-statusline) says, but I can't configure the colors nor the separators currently.

**Comment by Zeioth** [comment]
@vollowx I know. While nvchad and AstroNvim are ok distros, I don't normally recommend them to people because they ship their entire UI as a single plugin, which makes extremely difficult to understand what's going on on the inside.

This is a intentional way for them to keep the value their distros offer... Well, inside of their distros. But I believe any distro should have access to every feature in the Neovim ecosystem, which is why I created this and [NormalNvim](https://github.com/NormalNvim/NormalNvim).

You can probably find the colors somewhere on [their ui plugin](https://github.com/NvChad/ui).

**Comment by vollowx** [comment]
Actually we don't need to rebuild the whole statusline, as the link I gave [here](https://github.com/Zeioth/heirline-components.nvim/issues/2#issue-2133653285) AstroNvim offer a config for `heirline.nvim` to copy the look of NvChad's, the only problem is that I'm unable to get and set more highlights with `heirline-components.nvim`, nor the seperaters.

> This is a intentional thing they do to keep the value their distros offer... Well, inside of their distros, as they receive donations. But I believe any distro should have access to every feature in the Neovim ecosystem, which is why I created this and [NormalNvim](https://github.com/NormalNvim/NormalNvim).

Can't agree more, most of the distros keep everything strongly connected inside the distro, which makes it really hard for us to use 
a specified part of them, and `heirline-components.nvim` is really helpful for copying the config for `heirline.nvim` from AstroNvim, also reduces the time users need for configuring :+1: .

**Comment by Zeioth** [comment]
@vollowx on the heirline-components [how to install](https://github.com/Zeioth/heirline-components.nvim?tab=readme-ov-file#how-to-install) section
```
-- Heirline colors
heirline.load_colors(lib.hl.get_colors())
```

You can see the responsible one for setting the highlights is actually heirline, not us. we just provide a list of default colors you can check [here](https://github.com/Zeioth/heirline-components.nvim/blob/main/lua/heirline-components/core/env.lua).

That's how you change colors. If you need to change a highlight for a single instance of a component, you can do it by passing the argument `hl = { fg= "", bg = "" }`. For example:

```
require("heirline-components.all").component.breadcrumbs { hl = { fg = "", bg = "" } },
```

**Comment by vollowx** [comment]
> ```lua
> -- Heirline colors
> heirline.load_colors(require("heirline-components.all").hl.get_colors())
> ```

Yes, I'm just looking for some way to extend the color list

**Comment by Zeioth** [comment]
Feel free to re-open if you find any issue, or questions.

**Comment by vollowx** [comment]
Maybe we could expose the `get_hlgroup` API and let user extend the list of color provided for `heirline` by themselves, this way the components can follow the color of the current colorscheme, instead of hard-coded colors.

e.g.

```lua
local hl = require('heirline.utils').get_hlgroup

local get_colors = function()
  return vim.tbl_deep_extend('force', require('heirline-components.all').hl.get_colors(), {
    blank = { fg = hl('Normal').fg, bg = hl('StatusLine').bg },
    -- other colors, the default colors from your plugin will exist as long as the user doesn't override them
})
end

heirline.load_colors(get_colors())

-- autocmd stuff for ColorScheme, with heirline.on_colorscheme(colors...)
```

**Comment by Zeioth** [comment]
@vollowx can't you already do that? `get_colors()` return

```lua
{
  diagnostics_bg = 1447454,
  diagnostics_fg = 11121110,
  fg = 11121110,
  file_info_bg = 1447454,
  file_info_fg = 11121110,
  git_added = 2518378,
  git_branch_bg = 1447454,
  git_branch_fg = 12294903,
  git_changed = 5467294,
  git_diff_bg = 1447454,
  git_diff_fg = 11121110,
  git_removed = 11687259,
  inactive = "#16161e",
  insert = "#9ece6a",
  lsp_bg = 1447454,
  lsp_fg = 11121110,
  macro_recording_bg = 1447454,
  macro_recording_fg = 11121110,
  mode_bg = 1447454,
  mode_fg = 1447454,
  nav_bg = 1447454,
  nav_fg = 11121110,
  normal = "#7aa2f7",
  replace = "#f7768e",
  scrollbar = 2802654,
  section_bg = 1447454,
  section_fg = 11121110,
  tab_active_bg = 8037111,
  tab_active_fg = 1381918,
  tab_bg = 1447454,
  tab_close_bg = 1381918,
  tab_close_fg = 14371659,
  tab_fg = 3883617,
  tabline_bg = 1381918,
  tabline_fg = 1381918,
  terminal = "#9ece6a",
  treesitter_bg = 1447454,
  treesitter_fg = 10407530,
  virtual_env_bg = 1447454,
  virtual_env_fg = 12294903,
  visual = "#bb9af7",
  winbar_bg = 1447454,
  winbar_fg = 11121110,
  winbarnc_bg = 1447454,
  winbarnc_fg = 3883617
}
```

For every of the components:

```lua
"git_branch",
"file_info",
"git_diff",
"diagnostics",
"lsp",
"macro_recording",
"mode",
"cmd_info",
"treesitter",
"nav",
"virtual_env"
```
But that's quite overwhelming. I suggest either using global defaults with the `colors` option, or directly modifying the specific component you want like:
```lua
require("heirline-components.all").component.fill { hl = { fg = "#ebae34", bg = "#abb2bf" } }
```

In reality you shouldn't need to manually modify any color, as they will match your colorscheme by default already.

**Comment by Zeioth** [comment]
I documented this [here](https://github.com/Zeioth/heirline-components.nvim/wiki/colors)

**Comment by vollowx** [comment]
Sorry for the long delay.

Yes I can already do that by the present API, I didn't notice that.

Thanks again for making such a useful plugin!
