### ISSUE TITLE
`vim.t.bufs` is `nil` when loading dashboard.nvim

### ISSUE THREAD

**Issue by collins-lagat** [Zeioth/heirline-components.nvim#7]
With reference to this line... https://github.com/Zeioth/heirline-components.nvim/blob/823df01e391a01a53d57169a18e1957cea1be423/lua/heirline-components/core/init.lua#L290 ...`vim.t.buf` is `nil` when loading dashboard.nvim i.e. when calling `nvim` command with no args. However everything works great when directly opening a file or dir i.e. `nvim ~/.config/nvim`. I think using `alpha.vim` will not cause this problem but I could be wrong since I haven't tested it.
While looking for possible work arounds or solutions, I think the best place to solve the problem is in this module by handling the possible `nil` case. And edit that I have tested that works is:
```lua
vim.t.bufs = vim.tbl_filter(buf_utils.is_valid, vim.t.bufs or {})
```
This just provides a fallback value incase the key is nil. But I am open to other suggestions as I don't know the side-effects of passing an empty table to tbl_fitler.

**Comment by Zeioth** [comment]
Cannot repro.

@collins-lagat give me more detail:
* what's your neovim version?
* what effect do you experience?
* could you post a screenshot?

Make sure you are subscribing to the events like in the [how to install instructions](https://github.com/Zeioth/heirline-components.nvim?tab=readme-ov-file#how-to-install)

**Comment by Zeioth** [comment]
Even without repro I can tell your report is likely an actual bug. Fixed in https://github.com/Zeioth/heirline-components.nvim/commit/e8d88d250bae80e65b202209caf785baaeff27c6

**Comment by collins-lagat** [comment]
No problem but for the sake of context...
nvim: 0.10.0
screenshot: 
![Screenshot from 2024-06-10 18-35-23](https://github.com/Zeioth/heirline-components.nvim/assets/40242691/d67d283b-fce6-4df0-8d44-a320358a69ad)

**Comment by collins-lagat** [comment]
Thanks for the fix
