### ISSUE TITLE
🐛bug: highlight group of branch name with the new neovim default theme

### ISSUE THREAD

**Issue by eckig** [Zeioth/heirline-components.nvim#8]
### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows

### Describe the bug

With the new default neovim theme (both light and dark mode) the branch name in the statusbar is next to impossible to read, example:
![grafik](https://github.com/Zeioth/heirline-components.nvim/assets/8463899/7143c5cc-2581-4f40-b728-117433305d9b)

### Steps To Reproduce

1. start nvim with the new default theme
2. open file inside a git repository
3. watch the status line

### Expected Behavior

Branch name should be legible.

### Current Behavior

Branch name is nearly impossible to read.

**Comment by Zeioth** [comment]
@eckig check https://github.com/Zeioth/heirline-components.nvim/wiki/colors

**Comment by Zeioth** [comment]
This is not a bug. It depends of the colors of your colorscheme.

**Comment by eckig** [comment]
Thanks, I already figured that out.
I just thought, that the components should work for the new default color scheme out of the box.
